### ISSUE TITLE
installing .deb programs bugging my mousepad

### ISSUE THREAD

**Issue by cpicanco** [BunsenLabs/bunsen-configs#46] opened 2016-11-03 16:55 UTC
Installing programs using the GDebi packager installer (0.9.5.5+nmu1).

I am assuming that it is a BunsenLabs thing (somehow).

After installation (by clicking at the install button), the tapping of my mouse pad stops working (the one that simulates the left click).

I am fixing the problem this way:

``` bash
synclient TapButton1=1
```

PS.: Should I report this to GDebi on debian instead??

**Comment by johnraff** [comment] 2016-11-04 03:19
Hi cpicanco, I don't think this can be a BunsenLabs issue. If fact, that synclient setting is already in ~/.config/openbox/autostart.

**Comment by cpicanco** [comment] 2016-11-04 03:32
The problem is that it is being changed specifically when I install programs by clicking at the GDebi `install` button. Feel free to close the issue if you confirm it is not related to BunsenLabs configs (somehow).

**Comment by johnraff** [comment] 2016-11-04 05:56
The only place where BunsenLabs configures touchpad settings is ~/.config/openbox/autostart. 

I have just tested this on a laptop with a touchpad and cannot reproduce your issue.

I'm closing this - please feel free to post if you have some evidence that this is a Bunsen-related problem.

**Closed as completed by johnraff** 2016-11-04 05:56 UTC
Labels: invalid
